# Use root/example as user/password credentials
version: '3.7'

services:
  darknet:
    image: ubuntu
    container_name: ubuntu-darknet
    tty: "true"
    stdin_open: "true"
    volumes:
      - ../darknet:/darknet